### ISSUE TITLE
Possible solutions for the Concurrency problem !! 

### ISSUE THREAD

**Issue by aswinkumar1999** [mukheshpugal/rcube2#1]
AsyncIO -> [Check this out](https://www.skcript.com/svr/this-trick-will-make-you-perform-async-operation-in-python-like-a-pro/)

Also an other way of going through it is this : 

```
for infinity : 
           Get User Input 
           Check it Exited () 
           Do work () 
```

This retains all the History functionality while you just want the user to type just anything to exit , Not the best solution but the easiest I guess ... 

Or I guess the one we discussed - [Write to STDIN while exiting](https://stackoverflow.com/questions/15055524/write-function-result-to-stdin)

```
while True:
    data = input("Please enter the message:\n")
    if 'Exit' == data:
        break
    print(f'Processing Message from input() *****{data}*****')

print("Done")
```

[Check that here](https://www.journaldev.com/32137/read-stdin-python#2-using-input-function-to-read-stdin-data)

**Comment by mukheshpugal** [comment]
Thanks for the advice. I'm currently following code block 2. None of the solutions in the links seemed to fix the issue. Writing to stdin does not work while an input statement is active.

**Comment by aswinkumar1999** [comment]
Did you post it on Stackoverflow or something ? any progress on it ?

**Comment by mukheshpugal** [comment]
I haven't posted anywhere. I plan to exclude parallel threads in the final build.
